version: 2

refs:
  container: &container
    docker:
      - image: circleci/node:latest-browsers
    working_directory: ~/repo

jobs:
  all:
    <<: *container
    steps:
      - checkout
      - run:
          name: Versions
          command: node -v && npm -v && yarn -v
      - run:
          name: NPM Auth
          command: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
      - run:
          name: Install dependencies
          command: yarn install --frozen-lockfile
      - run:
          name: Build
          command: yarn build
      - run:
          name: Test
          command: yarn test
      - run:
          name: Test Functional
          command: yarn test:integration

  master:
    <<: *container
    steps:
      - checkout
      - run:
          name: Versions
          command: node -v && npm -v && yarn -v
      - run:
          name: NPM Auth
          command: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
      - run:
          name: Install dependencies
          command: yarn install --frozen-lockfile
      - run:
          name: Build
          command: yarn build
      - run:
          name: Test
          command: yarn test
      - run:
          name: Test Functional
          command: yarn test:integration
      - run:
          name: Release
          command: npx semantic-release
      - run:
          name: Post status to GitHub
          command: |
              npx cross-ci :run \
                  npx commit-status success Version "'\${BUILD_VERSION}'"

workflows:
  version: 2
  all:
    jobs:
      - all:
          filters:
            branches:
              ignore:
                - master
  master:
    jobs:
      - master:
          filters:
            branches:
              only: master