version: 2.1

refs:
  container: &container
    docker:
      - image: circleci/node:10-browsers
    working_directory: ~/repo

commands:
  install:
    steps:
      - run:
          name: NPM Auth - TODO Remove once tsconfig is public
          command: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "yarn.lock" }}
            - v1-dependencies-
      - run:
          name: Versions
          command: node -v && npm -v && yarn -v
      - run:
          name: Install dependencies
          command: yarn install --frozen-lockfile
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "yarn.lock" }}
  build:
    steps:
      - run:
          name: Build
          command: yarn build
  test:
    steps:
      - run:
          name: Prettier Check
          command: yarn prettier:check
      - run:
          name: TSLint
          command: yarn lint
      - run:
          name: Test
          command: yarn test
      - run:
          name: Test Functional
          command: yarn test:integration
  upload_artifacts:
    steps:
      - store_artifacts:
          path: ~/repo/src/test/image-tests-out
      - run:
          name: Post to GitHub
          command: |
            npx cross-ci :run \
              npx commit-status success Renderings \${BUILD_VERSION} "https://\${BUILD_NUM}-142040531-gh.circle-artifacts.com/0/home/circleci/repo/src/test/image-tests-out/index.html"
          when: always

jobs:
  all:
    <<: *container
    steps:
      - checkout
      - install
      - build
      - test
      - upload_artifacts

  master:
    <<: *container
    steps:
      - checkout
      - install
      - build
      - test
      - upload_artifacts
      - run:
          name: Release
          command: npx semantic-release

workflows:
  version: 2
  all:
    jobs:
      - all:
          filters:
            branches:
              ignore:
                - master
  master:
    jobs:
      - master:
          filters:
            branches:
              only: master
